DjangoApp1/DjangoApp1/urls.py
from django.contrib import admin
from django.urls import path, re_path
from first_app import views
from products import views as product_view
from products.views import ProductList, ProductDetailItem, ProductCreate, ProductUpdate, ProductDelete, MyBooksList, \
    ImageAdd, ImageDeleteView
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('register/', views.register_form, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('update_profile/', views.profile, name="update"),
    path('first_app/', include('first_app.urls')),
    path('update_password/', views.change_password, name="password_change"),
    path('cart/', product_view.Cart, name='cart'),
    path('add-to-cart/<int:pk>/', product_view.BookAddToCart, name='add-to-cart'),
    path('remove-from-cart/<int:pk>/', product_view.RemoveAllBooks, name='remove-from-cart'),
    path('remove-item-from-cart/<int:pk>/', product_view.BookRemoveFromCart,
         name='remove-single-item-from-cart'),
    path('books/', ProductList.as_view(), name="books"),
    path('mybooks/', MyBooksList.as_view(), name="mybooks"),
    path('books/<int:pk>/', ProductDetailItem.as_view(), name="book_item"),
    path('books/new/', ProductCreate.as_view(), name="book_new"),
    path('books/<int:pk>/update/', ProductUpdate.as_view(), name="book_update"),
    path('books/<int:pk>/add-image/', ImageAdd.as_view(), name="add-image"),
    path('books/<int:pk>/delete/', ProductDelete.as_view(), name="book_delete"),
    path('book/<int:book>/deleteimage/<int:pk>/', ImageDeleteView.as_view(), name='delete-image'),
    path('password/<str:email>/<str:token>/', views.new_password, name='new_password')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoApp1/first_app/urls.py
from first_app import views
from django.urls import path

app_name = 'home'

urlpatterns = [

    path('', views.index, name="index"),
    # path('form/', views.form_view, name="form"),
    # path('register/', views.register_form, name="register"),
    path('login/', views.user_login, name="login"),
    # path('logout/', views.user_logout, name="logout"),
    # path('update/', views.profile, name="update"),
    path('update_password/', views.change_password, name="password_change"),
    path('reset_password/', views.reset_password, name="password_reset"),
]

# path('custom_page/<str:id1>/<str:id2>/', views.custom_page, name='custom_page')

DjangoApp1/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

DjangoApp1/first_app/forms.py
from django import forms
# from first_app.models import Register
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm


# class FormName(forms.ModelForm):
#     # first_name = forms.CharField()
#     # last_name = forms.CharField()
#     # email = forms.EmailField()
#
#     class Meta():
#         model = Register
#         fields = '__all__'


# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())
#
#     class Meta():
#         model = User
#         fields = ('username', 'email', 'first_name', 'last_name', 'password')
#

class UserForm(UserCreationForm):
    username = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', ]


class PasswordReset(PasswordResetForm):
    username = forms.EmailField()

    class Meta:
        model = User
        fields = ['username']

class SetNewPassword(forms.Form):
    new_password1 = forms.CharField(
        label= ("New password"),
        widget=forms.PasswordInput,
        strip=False,
    )
    new_password2 = forms.CharField(
        label= ("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )

DjangoApp1/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from first_app.models import Register
from . import forms
import boto3
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from statsd import StatsClient
from django.contrib.auth import get_user_model
Users = get_user_model()
from django.contrib.auth.models import User
stats = StatsClient()
import logging
import uuid
logger = logging.getLogger(__name__)


# from statsd.defaults.django import statsd

def index(request):
    # user = request.user
    # if user:
    #     print('abc')
    #     # my_data = {'user': user.first_name}
    # # users = Register.objects.order_by('first_name')
    logger.info('User is here')
    return render(request, 'books/books.html', {})


@login_required
def user_logout(request):
    timer = stats.timer('user-logged-out')
    timer.start()
    logger.info('User logged out')
    logout(request)
    timer.stop()
    return HttpResponseRedirect(reverse('login'))


# def form_view(request):
#     form = forms.FormName()
#     if request.method == 'POST':
#         form = forms.FormName(request.POST)
#         if form.is_valid():
#             print('Validated')
#             print("fName: " + form.cleaned_data['first_name'])
#             print("lName: " + form.cleaned_data['last_name'])
#             print("email: " + form.cleaned_data['email'])
#             form.save(commit=True)
#             return index(request)
#         else:
#             print('Error')
#
#     return render(request, 'first_app/form.html', {'form': form})


def register_form(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('index'))
    registered = False
    reg_form = forms.UserForm()
    if request.method == 'POST':
        reg_form = forms.UserForm(data=request.POST)
        if reg_form.is_valid():
            # user = reg_form.save()
            # user.set_password(user.password)
            # user.save()
            timer = stats.timer('user-registered')
            timer.start()
            reg_form.save()
            username = reg_form.cleaned_data.get('username')
            raw_password = reg_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            logger.info('User Registered in')
            registered = True
            timer.stop()
            return HttpResponseRedirect(reverse('books'))

        else:
            print(reg_form.errors)
            logger.warning(reg_form.errors)
    else:
        reg_form = forms.UserForm()
    return render(request, 'first_app/registration.html', {'registered': registered, 'reg_form': reg_form})


# def user_login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         user = authenticate(username=username, password=password)
#         print(user)
#         print("-------")
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 print('AAAAAAAAA')
#                 return HttpResponseRedirect(reverse('index'))
#             else:
#                 print('BBBBBBBBB')
#                 return HttpResponse("Error")
#         else:
#             print('KKKKKKKKKK')
#             print('id:{} and pass:{}'.format(username, password))
#             return HttpResponse("Invalid Login Details")
#     else:
#         print('Oooooooooooo')
#         return render(request, 'first_app/login.html', {})

def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('books'))
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            timer = stats.timer('user-logged-in')
            timer.start()
            login(request, user)
            logger.info('User Logged in')
            timer.stop()
            return HttpResponseRedirect(reverse('books'))
        else:
            form = AuthenticationForm(request.POST)
            messages.info(request, "Invalid Credentials.")
            logger.warning('User entered invalid credentials')
            return render(request, 'first_app/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'first_app/login.html', {'form': form})


def profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            update_form = forms.UserUpdateForm(request.POST, instance=request.user)
            if update_form.is_valid():
                timer = stats.timer('user-profile-updated')
                timer.start()
                update_form.save()
                messages.success(request, "Account has been updated")
                timer.stop()
                return HttpResponseRedirect(reverse('update'))
        else:
            update_form = forms.UserUpdateForm(instance=request.user)
        context = {
            'update_form': update_form,
        }
        return render(request, 'first_app/form.html', context)
    else:
        return HttpResponseRedirect(reverse('login'))


def change_password(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(data=request.POST, user=request.user)
            if form.is_valid():
                timer = stats.timer('user-change-passwd')
                timer.start()
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, "Your Password has been updated!")
                timer.stop()
                return HttpResponseRedirect(reverse('logout'))
            else:
                messages.info(request, "Passwords Don't Match.")
                return render(request, 'first_app/password.html', {'form': form})
        else:
            form = PasswordChangeForm(user=request.user)
            return render(request, 'first_app/password.html', {'form': form})
    else:
        return HttpResponseRedirect(reverse('login'))


def reset_password(request):
    if request.method == 'POST':
        form = forms.PasswordResetForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('email')
            if User.objects.filter(username=username).exists():
                user1= User.objects.filter(username=username)
                token = uuid.uuid1()
                messages.success(request, "Your Password Reset Link in sent!")
                client = boto3.client('sns',region_name='us-east-1')
                msg={"username": username,"token":str(token)}
                response = client.publish(
                    TargetArn='arn:aws:sns:us-east-1:708581696554:user-updates-pwd',
                    Message=json.dumps(msg),
                    MessageAttributes={
                    'username': {
                        'DataType': 'String',
                        'StringValue': username
                    },
                    'token': {
                        'DataType': 'String',
                        'StringValue': str(token)
                    }
                })
            else:
                messages.success(request, "You are not registered as a user!")
                return HttpResponseRedirect(reverse('login'))
            return HttpResponseRedirect(reverse('login'))
    else:
        form = forms.PasswordResetForm()
        return render(request, 'first_app/reset_password.html', {'form': form})

def new_password(request,email,token):
    if request.method == 'POST':
        form = forms.SetNewPassword(data=request.POST)
        if form.is_valid():
            password1 = form.cleaned_data.get('new_password1')
            password2 = form.cleaned_data.get('new_password2')
            if password1 and password2:
                if password1 != password2:
                    messages.success(request, "Your Password is mismatched!")
                    return render(request, 'first_app/reset_password_form.html', {'form': form})
                if User.objects.filter(username=email).exists():
                    user= User.objects.get(username=email)
                    user.set_password(password2)
                    user.save()
                    messages.success(request, "Your Password is changed! Login Again !!!!")
                    return HttpResponseRedirect(reverse('login'))
                else:
                    messages.success(request, "User is mismatched!")
                    return render(request, 'first_app/reset_password_form.html', {'form': form})
    else:
        form = forms.SetNewPassword()
        return render(request, 'first_app/reset_password_form.html', {'form': form})

DjangoApp1/templates/first_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <!-- or -->
    <link href='https://unpkg.com/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <meta charset="UTF-8">
    <title>Demo WebSite</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'books' %}">E-commerce App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'books' %}">Books</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'mybooks' %}">MyBooks</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Profile
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'update' %}">Update Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Update Password</a>
                </div>
            </li>
        </ul>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart' %}">View Cart </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'book_new' %}">Add New Book</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block body_block %}

    {% endblock %}

</div>

</body>
</html>

DjangoApp1/templates/first_app/form.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <h5>Your username and email id is {{ user.username }}</h5>
    <form action="" method="post">
        {{ update_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

DjangoApp1/templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% block body_block %}

    {% csrf_token %}
    {% if user %}
        <div class="container">
            <h1>Welcome {{ user.first_name }} {{ user.last_name }}</h1>
        </div>
    {% endif %}

{% endblock %}

DjangoApp1/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <h1>Login </h1>

    <div class="jumbotron">

        {% if msg %}
            <li>
                <ol>{{ msg }}</ol>
            </li>
            {% else %}
            {{ " " }}
        {% endif %}

        <form action="{% url 'home:login' %}" method="post" enctype="multipart/form-data">
            {#        <form action="" method="post" enctype="multipart/form-data">#}
            {% csrf_token %}

            <label for="email">Username:</label>

            <input type="text" name="username">

            <label for="email">Password:</label>

            <input type="password" name="password">

            <input type="submit" value="Login" class="btn btn-primary">
            <a for="reset_password" href="{% url 'home:password_reset' %}">Forget Password ? </a>
        </form>

    </div>
{% endblock %}

DjangoApp1/templates/first_app/password.html
{% extends "first_app/base.html" %}
{% block body_block %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock body_block %}

DjangoApp1/templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <h1>Register Here</h1>
    <div class="jumbotron">

    {% if registered %}
        {% csrf_token %}
        <h1>You are Registered</h1>
    {% else %}

        <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ reg_form.as_p }}
        <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
    </div>
{% endblock %}

DjangoApp1/templates/first_app/reset_password.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    

    <div class="jumbotron">

        {% if msg %}
            <li>
                <ol>{{ msg }}</ol>
            </li>
            {% else %}
            {{ " " }}
        {% endif %}

        <form method="post" enctype="multipart/form-data">
            
            {% csrf_token %}

            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>

    </div>
{% endblock %}

DjangoApp1/templates/first_app/reset_password_form.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <h1>Reset Password</h1>

    <div class="jumbotron">

        {% if msg %}
            <li>
                <ol>{{ msg }}</ol>
            </li>
            {% else %}
            {{ " " }}
        {% endif %}

        <form method="post" enctype="multipart/form-data">
            
            {% csrf_token %}

            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>

    </div>
{% endblock %}